# Auto-generated by scripts/create-backend.sh
# Do not edit manually — re-run the script to regenerate.
# Passed to OpenTofu at init time:
#   tofu init -backend-config=envs/prod/backend.hcl -reconfigure

resource_group_name  = "rg-terraform-state-isar234-prod"
storage_account_name = "stisar234prodccd5b2b7"
container_name       = "tfstate"
key                  = "prod.tfstate"
use_oidc             = true
