# Auto-generated by scripts/create-backend.sh
# Do not edit manually — re-run the script to regenerate.
# Passed to OpenTofu at init time:
#   tofu init -backend-config=envs/dev/backend.hcl -reconfigure

resource_group_name  = "rg-terraform-state-isar2351-dev"
storage_account_name = "stisar2351devccd5b2b7"
container_name       = "tfstate"
key                  = "dev.tfstate"
use_oidc             = true
