# ==========================================================
# DEV — Compute & Workload SP — generated by Setup Wizard
# ==========================================================

# Compute: Interactive Clusters
clusters = {}
interactive_max_clusters_per_user = 5

# Compute: SQL Warehouses
sql_warehouses = {}

# Workload Service Principal
enable_workload_sp = false
