# ==========================================================
# DEV Environment Variables — generated by Setup Wizard
# ==========================================================

# Environment Identification
environment     = "dev"
subscription_id = "ccd5b2b7-67b3-42a2-a189-f512dd10c299"
bootstrap_mode  = false

# Resource Naming
resource_group_name       = "rg-lakehouse-dev"
databricks_workspace_name = "dbw-lakehouse-dev"
catalog_name              = "lakehouse_dev"
storage_account_prefix    = "dlhdev"

# Unity Catalog Metastore Configuration
unity_catalog_metastore_mode = "auto"

# Observability
log_retention_days = 30

# Network Configuration
enable_vnet_injection = false
enable_public_access  = true
enable_private_endpoint = false
vnet_name          = "vnet-lakehouse-dev"
vnet_address_space = [
  "10.100.0.0/16",
]
public_subnet_address_prefixes  = [
  "10.100.1.0/24",
]
private_subnet_address_prefixes = [
  "10.100.2.0/24",
]

# Storage Accounts (ADLS Gen2)
storage_accounts = {
  "lake" = {
    containers       = [
      "metastore",
      "landing",
      "raw",
      "curated",
      "core",
      "mart",
      "reporting",
      "sharing",
    ]
    replication_type = "LRS"
  }
}

# Security Configuration
key_vault_allowed_ips = []
enable_ip_access_lists = false
governance_allowed_ips = []

# Environment-Specific Tags
tags = {
  "Environment" = "dev"
  "Purpose" = "Development and Testing"
}

# CI/CD Configuration
cicd_sp_application_id = "17833302-b82d-41d6-995d-3954dbe45115"
