# ==========================================================
# DEV — Unity Catalog Grants — generated by Setup Wizard
# ==========================================================

# Unity Catalog Grants
catalog_grants = {
  admins = {
    principal  = "Databricks-Admins-Dev"
    privileges = ["ALL_PRIVILEGES"]
  }
  engineers = {
    principal  = "Databricks-Engineers-Dev"
    privileges = ["USE_CATALOG"]
  }
  analysts = {
    principal  = "Databricks-Analysts-Dev"
    privileges = ["USE_CATALOG"]
  }
  stewards = {
    principal  = "Databricks-Stewards-Dev"
    privileges = ["USE_CATALOG", "APPLY_TAG"]
  }
  users = {
    principal  = "Databricks-Users-Dev"
    privileges = ["USE_CATALOG"]
  }
}

# Schema Grants
schema_grants = {
  "landing" = {
    engineers = {
      principal  = "Databricks-Engineers-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "CREATE_VOLUME", "SELECT", "MODIFY", "READ_VOLUME", "WRITE_VOLUME"]
    }
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "SELECT", "APPLY_TAG"]
    }
  }
  "raw" = {
    engineers = {
      principal  = "Databricks-Engineers-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "CREATE_VOLUME", "SELECT", "MODIFY", "READ_VOLUME", "WRITE_VOLUME"]
    }
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "SELECT", "APPLY_TAG"]
    }
  }
  "curated" = {
    engineers = {
      principal  = "Databricks-Engineers-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "SELECT", "MODIFY"]
    }
    analysts = {
      principal  = "Databricks-Analysts-Dev"
      privileges = ["USE_SCHEMA", "SELECT"]
    }
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "SELECT", "APPLY_TAG"]
    }
  }
  "core" = {
    engineers = {
      principal  = "Databricks-Engineers-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "SELECT", "MODIFY"]
    }
    analysts = {
      principal  = "Databricks-Analysts-Dev"
      privileges = ["USE_SCHEMA", "SELECT"]
    }
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "SELECT", "APPLY_TAG"]
    }
  }
  "mart" = {
    engineers = {
      principal  = "Databricks-Engineers-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "SELECT", "MODIFY"]
    }
    analysts = {
      principal  = "Databricks-Analysts-Dev"
      privileges = ["USE_SCHEMA", "SELECT"]
    }
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "SELECT", "APPLY_TAG"]
    }
    users = {
      principal  = "Databricks-Users-Dev"
      privileges = ["USE_SCHEMA", "SELECT"]
    }
  }
  "reporting" = {
    analysts = {
      principal  = "Databricks-Analysts-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "SELECT", "MODIFY"]
    }
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "SELECT", "APPLY_TAG"]
    }
    users = {
      principal  = "Databricks-Users-Dev"
      privileges = ["USE_SCHEMA", "SELECT"]
    }
  }
  "sharing" = {
    stewards = {
      principal  = "Databricks-Stewards-Dev"
      privileges = ["USE_SCHEMA", "CREATE_TABLE", "SELECT", "MODIFY", "APPLY_TAG"]
    }
  }
}
