# ==========================================================
# DEV — AIM (Azure AD → Databricks) Groups — generated by Setup Wizard
# ==========================================================

aim_groups = {
  admins = {
    display_name               = "Databricks-Admins-Dev"
    description                = "Dev workspace administrators with full access"
    mail_nickname              = "databricks-admins-dev"
    allow_cluster_create       = true
    allow_instance_pool_create = true
  }
  engineers = {
    display_name               = "Databricks-Engineers-Dev"
    description                = "Dev Data Engineers — self-service cluster creation enabled"
    mail_nickname              = "databricks-engineers-dev"
    allow_cluster_create       = true
    allow_instance_pool_create = false
  }
  analysts = {
    display_name               = "Databricks-Analysts-Dev"
    description                = "Dev Data Analysts with read access to silver/gold layers"
    mail_nickname              = "databricks-analysts-dev"
    allow_cluster_create       = false
    allow_instance_pool_create = false
  }
  stewards = {
    display_name               = "Databricks-Stewards-Dev"
    description                = "Dev Data Stewards for governance and metadata management"
    mail_nickname              = "databricks-stewards-dev"
    allow_cluster_create       = false
    allow_instance_pool_create = false
  }
  users = {
    display_name               = "Databricks-Users-Dev"
    description                = "Dev standard users with limited access"
    mail_nickname              = "databricks-users-dev"
    allow_cluster_create       = false
    allow_instance_pool_create = false
  }
}

# Pre-created Azure AD group object IDs (written by create-azure-groups.sh).
# Terraform uses these directly — CI/CD SP needs no Group.ReadWrite.All.
aim_group_ids = {
  admins = "aa02553e-9fee-4b63-935a-f50147c284b2"
  engineers = "234444a2-2d27-4eea-9988-d2fd18f9abf3"
  analysts = "cc3121fa-12d0-4b10-98a4-af651d27091b"
  stewards = "05b5a97f-e73c-4999-83ee-a9d86f801863"
  users = "cd38b1e1-4c53-4c8c-a887-6b52e3bde141"
}
